### ISSUE TITLE
Check and maybe reconfigure signup link

### ISSUE THREAD

**Issue by g-simmons** [g-simmons/llm_persona_website#2]
There is a signup link somewhere on the site. I don't know what it does!

We should check to make sure that this goes to an email or other inbox that is being monitored.

If it is misconfigured, we should reconfigure it.

**Comment by wuyudaxia** [comment]
This issue is fixed, by updating the API key. 

After changing the API key, it works, and there is a email sent to my testing email. However, we still have to change the settings in the EmailJS.

**Comment by g-simmons** [comment]
@wuyudaxia What settings need to be changed? If you're confident about the appropriate changes, please go ahead and commit them directly. If you're not so sure, please open a PR and I can review the changes :)

**Comment by wuyudaxia** [comment]
@g-simmons 

Hi! The total setting which need to be changed is the `index.html` file, I changed the API key into a new one I registered yesterday.

I think this should work by updating the API key, and I have pushed it into the branch `dev`. But there is a problem that cause it is a html file, and the API tokens will directly post to everyone.

So I am thinking to make a backend for our web page server.

**Comment by g-simmons** [comment]
I think a backend might complicate long-term maintenance. Can we just create a contact email and list it on the site, instead of using a "Contact Us" form?

**Comment by wuyudaxia** [comment]
I think that would be a reasonable solution, but after my consideration, I think it is OK for us to open the API key to the public, since we can only use the API key to send email to our official club email, and it will not result in issues.

**Comment by wuyudaxia** [comment]
In this way, we do not need an backend, but also we may let this webpage remains the same.

**Comment by g-simmons** [comment]
Sure. If the only thing the API key does is send emails to our contact email, it seems ok to have it listed publicly. 

Am I correct that the worst-case scenario here is we get spammed with lots of emails? Do you know if we are paying for this service? If there is a $ cost per email, then maybe we should hide the API key.

**Comment by wuyudaxia** [comment]
Yes, the worst-case senario here is that we will be spammed with lots of emails. And currently, we may use the free-plan with a limit of 100 messages per day, so that we will not have to pay for the APIs.

**Comment by g-simmons** [comment]
Sounds good! I'm happy with this solution :)

**Comment by wuyudaxia** [comment]
I have found how the emailjs work! I believe it may work as we decided.

![image](https://github.com/user-attachments/assets/e4f27a58-2256-48a4-aea7-1eef8c399be3)
![image](https://github.com/user-attachments/assets/3ebd7f50-5a87-419b-a629-ccacbc1e8757)
